services:
  wandb:
    image: wandb/local:latest
    ports:
      - "8080:8080"
    volumes:
      - wandb-data:/vol
    environment:
      - LOCAL_STORAGE_PATH=/vol
    restart: unless-stopped

volumes:
  wandb-data:
    name: wandb-demo-data
